"""Inert, deterministic epistemic-orchestra contracts and CPT compilation."""

from runtime.epistemic_orchestra.canonical import (
    EpistemicContractError,
    canonical_json_bytes,
    canonical_sha256,
    exact_text_sha256,
)
from runtime.epistemic_orchestra.contracts import (
    CRITIC_PAYLOAD_SCHEMA_VERSION,
    EMPTY_KNOWLEDGE_CONTEXT_HASH,
    EMPTY_KNOWLEDGE_PROFILE_HASH,
    RUN_SCHEMA_VERSION,
    STAGE_SCHEMA_VERSION,
    CriticIssue,
    CriticOutcome,
    CriticSeverity,
    CriticStagePayload,
    EpistemicRunContract,
    EpistemicStageContract,
    OrchestrationMode,
    StageRole,
    TruncationEvidence,
    build_critic_stage_payload,
    build_epistemic_run_contract,
    build_epistemic_stage_contract,
    build_truncation_evidence,
    compute_stage_plan_hash,
    parse_critic_stage_payload,
    validate_critic_payload_against_stage,
    validate_stage_against_run,
    validate_stage_parent_binding,
    validate_stage_replay_state,
    verify_epistemic_stage_chain,
)
from runtime.epistemic_orchestra.cpt_stage import (
    CriticStageCompilation,
    RevisionCompilation,
    RevisionDisposition,
    bind_cpt_transformation_to_stage,
    compile_critic_stage,
    compile_revision_request,
    hash_critic_transformation_record,
    validate_revision_compilation,
)


__all__ = [
    "CRITIC_PAYLOAD_SCHEMA_VERSION",
    "EMPTY_KNOWLEDGE_CONTEXT_HASH",
    "EMPTY_KNOWLEDGE_PROFILE_HASH",
    "RUN_SCHEMA_VERSION",
    "STAGE_SCHEMA_VERSION",
    "CriticIssue",
    "CriticOutcome",
    "CriticSeverity",
    "CriticStageCompilation",
    "CriticStagePayload",
    "EpistemicContractError",
    "EpistemicRunContract",
    "EpistemicStageContract",
    "OrchestrationMode",
    "RevisionCompilation",
    "RevisionDisposition",
    "StageRole",
    "TruncationEvidence",
    "bind_cpt_transformation_to_stage",
    "build_critic_stage_payload",
    "build_epistemic_run_contract",
    "build_epistemic_stage_contract",
    "build_truncation_evidence",
    "canonical_json_bytes",
    "canonical_sha256",
    "compile_critic_stage",
    "compile_revision_request",
    "compute_stage_plan_hash",
    "exact_text_sha256",
    "hash_critic_transformation_record",
    "parse_critic_stage_payload",
    "validate_critic_payload_against_stage",
    "validate_revision_compilation",
    "validate_stage_against_run",
    "validate_stage_parent_binding",
    "validate_stage_replay_state",
    "verify_epistemic_stage_chain",
]
