"""Schema-version catalogue for provider-independent knowledge context."""

from runtime.knowledge_modules.context import (
    CONTEXT_EVIDENCE_SCHEMA_VERSION,
    CONTEXT_FAILURE_SCHEMA_VERSION,
    CONTEXT_MODULE_SECTION_SCHEMA_VERSION,
    CONTEXT_PACKAGE_SCHEMA_VERSION,
)
from runtime.knowledge_modules.context_policy import (
    CONTEXT_LIMITS_SCHEMA_VERSION,
    RESPONSE_POLICY_SCHEMA_VERSION,
)
from runtime.knowledge_modules.provider_target import PROVIDER_TARGET_SCHEMA_VERSION


KNOWLEDGE_CONTEXT_SCHEMA_VERSIONS = (
    CONTEXT_EVIDENCE_SCHEMA_VERSION,
    CONTEXT_FAILURE_SCHEMA_VERSION,
    CONTEXT_LIMITS_SCHEMA_VERSION,
    CONTEXT_MODULE_SECTION_SCHEMA_VERSION,
    CONTEXT_PACKAGE_SCHEMA_VERSION,
    PROVIDER_TARGET_SCHEMA_VERSION,
    RESPONSE_POLICY_SCHEMA_VERSION,
)


__all__ = ("KNOWLEDGE_CONTEXT_SCHEMA_VERSIONS",)
