"""Stable schema-version catalogue for the generic Knowledge Hub 1B contracts."""

from runtime.knowledge_modules.composite import (
    COMPOSITE_BUNDLE_SCHEMA_VERSION,
    EXECUTION_RESULT_SCHEMA_VERSION,
    ITEM_PROVENANCE_SCHEMA_VERSION,
    MODULE_INSTANCE_BUNDLE_SCHEMA_VERSION,
)
from runtime.knowledge_modules.instances import (
    CONTROL_RECORD_SCHEMA_VERSION,
    INSTANCE_REGISTRATION_SCHEMA_VERSION,
    INSTANCE_SCHEMA_VERSION,
)
from runtime.knowledge_modules.planning import (
    COMPOSITE_QUERY_PLAN_SCHEMA_VERSION,
    KNOWLEDGE_QUERY_SCHEMA_VERSION,
    MODULE_QUERY_PLAN_SCHEMA_VERSION,
)
from runtime.knowledge_modules.policy import POLICY_SCHEMA_VERSION
from runtime.knowledge_modules.profiles import (
    PROFILE_MODULE_SCHEMA_VERSION,
    PROFILE_SCHEMA_VERSION,
)
from runtime.knowledge_modules.registry import MODULE_REGISTRATION_SCHEMA_VERSION
from runtime.knowledge_modules.transports import TRANSPORT_SCHEMA_VERSION


KNOWLEDGE_MODULE_CONTROL_PLANE_SCHEMA_VERSIONS = (
    COMPOSITE_BUNDLE_SCHEMA_VERSION,
    COMPOSITE_QUERY_PLAN_SCHEMA_VERSION,
    CONTROL_RECORD_SCHEMA_VERSION,
    EXECUTION_RESULT_SCHEMA_VERSION,
    INSTANCE_REGISTRATION_SCHEMA_VERSION,
    INSTANCE_SCHEMA_VERSION,
    ITEM_PROVENANCE_SCHEMA_VERSION,
    KNOWLEDGE_QUERY_SCHEMA_VERSION,
    MODULE_INSTANCE_BUNDLE_SCHEMA_VERSION,
    MODULE_QUERY_PLAN_SCHEMA_VERSION,
    MODULE_REGISTRATION_SCHEMA_VERSION,
    POLICY_SCHEMA_VERSION,
    PROFILE_MODULE_SCHEMA_VERSION,
    PROFILE_SCHEMA_VERSION,
    TRANSPORT_SCHEMA_VERSION,
)


__all__ = ("KNOWLEDGE_MODULE_CONTROL_PLANE_SCHEMA_VERSIONS",)
